export interface ICard {
  code: string;
  pack_code: string;
  pack_name: string;
  card_set_code: string;
  card_set_name: string;
  card_set_type_name_code?: string;
  name: string;
  url: string;
  type_code: string;
  type_name: string;
  text?: string;
  subname?: string;
  imagesrc?: string;
  attack?: number;
  attack_cost?: number;
  attack_text?;
  back_flavor?;
  back_name?;
  back_text?;
  backimagesrc?;
  base_threat?: number;
  base_threat_fixed?: boolean;
  boost?: number;
  boost_text?;
  cost?: number;
  deck_limit?: number;
  double_sided?: boolean;
  escalation_threat?: number;
  escalation_threat_fixed?: boolean;
  faction_code?: string;
  faction_name?: string;
  flavor?;
  health?: number;
  health_per_hero?;
  hidden?;
  illustrator?;
  is_unique?: boolean;
  linked_card?;
  linked_to_code?;
  linked_to_name?;
  octgn_id?;
  permanent?;
  position?;
  quantity?: number;
  real_name?: string;
  real_text?: string;
  real_traits?;
  resource_energy?: number;
  resource_mental?: number;
  resource_physical?: number;
  resource_wild?: number;
  scheme?;
  scheme_acceleration?: number;
  scheme_crisis?;
  scheme_hazard?;
  scheme_text?;
  set_position?;
  spoiler?;
  stage?;
  threat?;
  threat_fixed?;
  thwart?;
  thwart_cost?;
  traits?;
}
